Reporter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Reporter.Data;
using Reporter.Models;

namespace Reporter.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;


        
        public HomeController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        
        public IActionResult Index(int pg = 1)
        {
            var selling = _context.SalesTable.ToList();
            const int pageSize = 30;
            if (pg < 1)

                pg = 1;


            int recsCount = selling.Count();
            var pagination = new Pagination(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;


            var data = selling.Skip(recSkip).OrderByDescending(x => x.Date).Take(pagination.PageSize).ToList();
            this.ViewBag.Pagination = pagination;

            
            return View(data);
        }

    }
}

Reporter/Controllers/ImportController.cs
using System.IO;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Reporter.Models;

namespace Reporter.Controllers
{
    public class ImportController : Controller
    {


        private IWebHostEnvironment _env;
        private IConfiguration _config;
        public ImportController(IWebHostEnvironment environment, IConfiguration configuration)
        {
            _env = environment;
            _config = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload(Excel excel)
        {
            IFormFile file = excel.ExcelFile;
            string filePath = "";
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    try
                    {
                        //Create a Folder.
                        string path = Path.Combine(_env.WebRootPath, "Uploads");
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }

                        //Save the uploaded Excel file.
                        string fileName = Path.GetFileName(file.FileName);
                        filePath = Path.Combine(path, fileName);
                        using (FileStream stream = new FileStream(filePath, FileMode.Create))
                        {
                            file.CopyTo(stream);
                        }

                        //Read the connection string for the Excel file.
                        string connectionString = _config.GetConnectionString("ExcelConString");
                        DataTable dt = new DataTable();
                        connectionString = string.Format(connectionString, filePath);

                        using (OleDbConnection connExcel = new OleDbConnection(connectionString))
                        {
                            using (OleDbCommand cmdExcel = new OleDbCommand())
                            {
                                using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                                {
                                    cmdExcel.Connection = connExcel;

                                    //Get the name of First Sheet.
                                    connExcel.Open();
                                    DataTable dtExcelSchema;
                                    dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                                    string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                                    connExcel.Close();

                                    //Read Data from First Sheet.
                                    connExcel.Open();
                                    cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                                    odaExcel.SelectCommand = cmdExcel;
                                    odaExcel.Fill(dt);
                                    connExcel.Close();
                                }
                            }
                        }

                        //Insert the Data read from the Excel file to Database Table.
                        connectionString = _config.GetConnectionString("connectionString");
                        using (SqlConnection con = new SqlConnection(connectionString))
                        {
                            using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                            {
                                //Set the database table name.
                                sqlBulkCopy.DestinationTableName = "dbo.SalesTable";

                                //[OPTIONAL]: Map the Excel columns with that of the database table.


                                sqlBulkCopy.ColumnMappings.Add("Segment", "Segment");
                                sqlBulkCopy.ColumnMappings.Add("Country", "Country");
                                sqlBulkCopy.ColumnMappings.Add("Product", "Product");
                                sqlBulkCopy.ColumnMappings.Add("Discount Band", "DiscountBand");
                                sqlBulkCopy.ColumnMappings.Add("Units Sold", "UnitSold");
                                sqlBulkCopy.ColumnMappings.Add("Manufacturing Price", "ManufacturingPrice");
                                sqlBulkCopy.ColumnMappings.Add("Sale Price", "SalePrice");
                                sqlBulkCopy.ColumnMappings.Add("Gross Sales", "GrossSales");
                                sqlBulkCopy.ColumnMappings.Add("Discounts", "Discounts");
                                sqlBulkCopy.ColumnMappings.Add(" Sales", "Sales");
                                sqlBulkCopy.ColumnMappings.Add("COGS", "COGS");
                                sqlBulkCopy.ColumnMappings.Add("Profit", "Profit");
                                sqlBulkCopy.ColumnMappings.Add("Date", "Date");

                                con.Open();
                                sqlBulkCopy.WriteToServer(dt);
                                con.Close();
                                ViewBag.Message = "Import Successfully";

                            }
                        }


                    }
                    catch (System.Exception ex)
                    {

                        ViewBag.ErrorMessage = ex.Message;
                    }
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

            }
            return View("Index", excel);
        }
    }
}

Reporter/Views/Home/Index.cshtml
@model IEnumerable<Reporter.Models.SalesTable>


@{
    ViewData["Title"] = "Index";
    Pagination pagination = new Pagination();

    int count = 0;

    count +=  pagination.PageSize;
    int pageNo = 0;
    if (ViewBag.Pagination != null)
    {
        pagination = ViewBag.Pagination;
        pageNo = pagination.CurrentPage;

    }
}

<div class="card-body">
    <!-- Grid row -->
    <div class="row">
        <!-- Grid column -->
        <div class="col-md-12">
            <h2 class="py-3 text-center font-bold font-up blue-text">Table</h2>
        </div>
        <!-- Grid column -->
            <a class="btn btn-warning" asp-controller="Import" asp-action="Index">Import</a>
            <a class="btn btn-success" asp-controller="Email" asp-action="Index">Export</a>
    </div>
    <!-- Grid row -->
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Segment</th>
                    <th scope="col">Country</th>
                    <th scope="col">Product</th>
                    <th scope="col">Discount Band</th>
                    <th scope="col">Unit Sold</th>
                    <th scope="col">Manufacturing Price</th>
                    <th scope="col">Sale Price</th>
                    <th scope="col">Gross Sales</th>
                    <th scope="col">Discounts</th>
                    <th scope="col">Sales</th>
                    <th scope="col">COGS</th>
                    <th scope="col">Profit</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@(pagination.CurrentPage*count)</th>
                        <td>@item.Segment</td>
                        <td>@item.Country</td>
                        <td>@item.Product</td>
                        <td>@item.DiscountBand</td>
                        <td>@item.UnitSold</td>
                        <td>$   @item.ManufacturingPrice</td>
                        <td>$   @item.SalePrice</td>
                        <td>$   @item.GrossSales</td>
                        <td>$   @item.Discounts</td>
                        <td>$   @item.Sales</td>
                        <td>$   @item.COGS</td>
                        <td>$   @item.Profit</td>
                        <td>@item.Date</td>
                    </tr>

                }

            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-center">
        <!--Pagination -->
        <nav class="my-4 pt-2">
            @if (pagination.TotalPages > 0)
            {
                <ul class="pagination pagination-circle pg-blue mb-0">
                    <li class="page-item @(pagination.CurrentPage <=1 ? "disabled" : "") d-none d-md-block"><a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="@pageNo=1">First</a></li>
                    <li class="page-item @(pagination.CurrentPage <=1 ? "disabled" : "")">
                        <a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="@(pagination.CurrentPage - 1)">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    @if (pagination.StartPage > 2)
                    {
                        <li class="page-item">
                            <a class="page-link">
                                <span aria-hidden="true">. . .</span>

                            </a>
                        </li>
                    }
                    @for (var pge = pagination.StartPage; pge <= pagination.EndPage; pge++)
                    {
                        <li class="page-item @(pge == pagination.CurrentPage ? "active" : "")">
                            <a class="page-link" Home" asp-action="Index" asp-route-pg="@pge">@pge</a>
                        </li>
                    }
                    @if (pagination.CurrentPage < pagination.TotalPages - 2)
                    {
                        <li class="page-item">
                            <a class="page-link">
                                <span aria-hidden="true">. . .</span>

                            </a>
                        </li>
                    }
                    <li class="page-item @(pagination.CurrentPage >=pagination.TotalPages ? "disabled" : "") ">
                        <a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="@(pagination.CurrentPage + 1)">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>

                    <li class="page-item @(pagination.CurrentPage >=pagination.TotalPages ? "disabled" : "")  clearfix d-none d-md-block"><a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="@pagination.TotalPages">Last</a></li>
                </ul>
            }
        </nav>
        <!--/Pagination -->
    </div>
</div>